### ISSUE TITLE
Consider using hono?

### ISSUE THREAD

**Issue by nickchomey** [thepassle/swtl#12]
Hey there, I wonder if you would consider using hono here rather than your custom router etc... Perhaps being written in TS makes it a non-starter, though it is becoming increasingly easy to work with TS with things like Deno. The tradeoff would be maximal isomorphism - it seems to work, essentially, _everywhere_ due to using web standards. https://hono.dev/docs/#web-standards

You'll even see that their [PatternRouter](https://hono.dev/docs/concepts/routers#patternrouter) just [uses raw Regex](https://github.com/honojs/hono/pull/1036#issuecomment-1519368200) rather than the URLPattern API, which they say brings better compatibility and performance. 

It has [streaming](https://hono.dev/docs/helpers/streaming) as well. 

Also, you could offload some of the maintenance and development since it is very popular and well-supported (Dev was hired by Cloudflare to work on it, and it is [used in many of their products](https://blog.cloudflare.com/the-story-of-web-framework-hono-from-the-creator-of-hono/)), and allow for much more functionality through their middleware etc... 

Or, in addition to TS overhead, would it interfere with the iterable templates?

Anyway, just some food for thought!

**Comment by thepassle** [comment]
Hi!

I'm probably not going to do that, but you can use swtl templates with Hono, here's an example:

```js
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { html, HtmlResponse } from 'swtl';

const app = new Hono();

app.get('/', () => new HtmlResponse(html`<h1>hello</h1>`));

serve({
  fetch: app.fetch,
  port: 3000,
});

```
