### ISSUE TITLE
double slash is detected as closing tag in some cases

### ISSUE THREAD

**Issue by gryzzly** [thepassle/swtl#2]
The following seems to break for me, cutting the output at `=https:`. 
```
render: ({params, query, request}) => html`
  <${Html} title="swtl">
    <div>
      <iframe src="https://example.com/page.html"></iframe>
    </div>
<//>`
```
results in 
<img width="331" alt="Screenshot 2023-11-28 at 01 25 55" src="https://github.com/thepassle/swtl/assets/26131/f676815a-dcce-4c99-b16c-aaf5781ca2ee">

I tried to monkey patch by adding a check for a preceding angle bracket, it seems to fix my case at least:
in html.js, line 228:
```
// added the first check 
if (statics[i][j] == "<"&& statics[i][j + 1] === "/" && statics[i][j + 2] === "/") {
```

**Comment by thepassle** [comment]
Nice, would you mind opening a PR for this? And maybe we can add a test for this, too
